db:
  drivers:
    default:
      file: "./database/app.db"
      type: sqlite
      maxIdleConns: 10
      maxOpenConns: 100
mongodb:
  drivers:
    default:
      host: localhost
      port: 27017
      database: duxgo
      username: ""
      password: ""
redis:
  drivers:
    default:
      db: 0
      host: localhost
      password: ""
      port: 6379
