driver:
  maxsize: 10240
  type: qiniu
  local:
    path: ./uploads
    domain: http://0.0.0.0:8080
  qiniu:
    accessKey: 0AFgqoXKorAd4R2T2MytmOsvPaaxKAOoKZ2Ju-nm
    secretKey: uy1RLddGE2dWWpS7M-m4WdWKHSRNsH9JSRmLyxAD
    bucket: s3-cn-south-1.qiniucs.com
    domain: http://cdn.xxxx.com